apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "hive-metastore.fullname" . }}-db-init-schema
spec:
  template:
    spec:
      containers:
        - name: hivemeta
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Checking if schema exists...";
              if schematool --verbose -info -dbType postgres -userName ${username} -passWord ${password} -url "jdbc:postgresql://{{ tpl .Values.connections.database.host . }}:{{ tpl .Values.connections.database.port . }}/{{ tpl .Values.connections.database.database . }}" > /dev/null 2>&1; then
                echo "Schema exists, running -upgradeSchema...";
                schematool --verbose -upgradeSchema -dbType postgres -userName ${username} -passWord ${password} -url "jdbc:postgresql://{{ tpl .Values.connections.database.host . }}:{{ tpl .Values.connections.database.port . }}/{{ tpl .Values.connections.database.database . }}"
              else
                echo "Schema does not exist, running -initSchema...";
                schematool --verbose -initSchema -ifNotExists -dbType postgres -userName ${username} -passWord ${password} -url "jdbc:postgresql://{{ tpl .Values.connections.database.host . }}:{{ tpl .Values.connections.database.port . }}/{{ tpl .Values.connections.database.database . }}"
              fi
          volumeMounts:
            - name: hive-config
              mountPath: /opt/hive-metastore/conf
          env:
            {{- if .Values.extraEnvVars }}
            {{- include "common.tplvalues.render" (dict "value" .Values.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          {{- if .Values.envFromSecret }}
          envFrom:
            - secretRef:
                name: {{ tpl .Values.envFromSecret . | quote }}
          {{- end }}
      volumes:
        - name: hive-config
          configMap:
            name: {{ include "hive-metastore.fullname" . }}


      restartPolicy: Never
  backoffLimit: 3
